name: Continuous Integration

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          # 使用npm缓存
          cache: npm

      # 安装依赖
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 运行TypeScript类型检查
      - name: TypeScript check
        run: npx vue-tsc --noEmit

      # 运行ESLint检查 - 暂时禁用以解决Node.js 18兼容性问题
      # - name: ESLint check
      #   run: npm run lint

      # # 运行测试
      # - name: Run tests
      #   run: npm test

      # 构建生产环境代码
      - name: Build production
        run: npm run build

      # # 构建预发布环境代码
      # - name: Build staging
      #   run: npm run build:staging
