name: Code Quality Check

on:
  pull_request:
    branches: [master]

jobs:
# Code quality checks temporarily disabled due to ESLint compatibility issues
# Will be re-enabled after resolving compatibility with Node.js 18
