name: Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.2.0

      - name: Install dependencies
        run: pnpm install

      - name: ESLint Review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.MOBVUE }}
          reporter: github-pr-review
          level: warning
          eslint_flags: ". --ext .ts,.tsx,.vue,.js,.jsx --fix=false"

      - name: Size Check
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.MOBVUE }}
          skip_step: install

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.2.0

      - name: Install dependencies
        run: pnpm install

      - name: Audit dependencies
        run: pnpm audit --prod

      - name: Check for outdated dependencies
        run: pnpm outdated --json > outdated.json || true

      - name: Upload outdated dependencies report
        uses: actions/upload-artifact@v4
        with:
          name: outdated-dependencies
          path: outdated.json
